M48
; DRILL file {KiCad 7.0.6} date Mon 07 Aug 2023 11:18:21 AM CDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-07T11:18:21-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X150.88Y-119.09
X157.88Y-119.09
T2
X172.03Y-91.48
T0
M30
