// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Smartwatch

#include "../ui.h"

void ui_watch_analog_screen_init(void)
{
    ui_watch_analog = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_watch_analog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_analog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_analog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_bg_2 = lv_img_create(ui_watch_analog);
    lv_img_set_src(ui_bg_2, &ui_img_bg1_png);
    lv_obj_set_width(ui_bg_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bg_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bg_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bg_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bg_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_battery_group1 = ui_batterygroup_create(ui_watch_analog);
    lv_obj_set_x(ui_battery_group1, -4);
    lv_obj_set_y(ui_battery_group1, 187);

    ui_clock_group = lv_obj_create(ui_watch_analog);
    lv_obj_set_width(ui_clock_group, 350);
    lv_obj_set_height(ui_clock_group, 350);
    lv_obj_set_align(ui_clock_group, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clock_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clock_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clock_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sec = lv_img_create(ui_clock_group);
    lv_img_set_src(ui_sec, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sec, -2);
    lv_obj_set_y(ui_sec, -61);
    lv_obj_set_align(ui_sec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sec, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_sec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_sec, 15, 155);
    lv_img_set_angle(ui_sec, 12000);
    lv_img_set_zoom(ui_sec, 180);

    ui_min = lv_img_create(ui_clock_group);
    lv_img_set_src(ui_min, &ui_img_clockwise_min_png);
    lv_obj_set_width(ui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min, -3);
    lv_obj_set_y(ui_min, -70);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_min, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_min, 9, 153);
    lv_img_set_zoom(ui_min, 180);

    ui_hour = lv_img_create(ui_clock_group);
    lv_img_set_src(ui_hour, &ui_img_clockwise_hour_png);
    lv_obj_set_width(ui_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hour, -3);
    lv_obj_set_y(ui_hour, -37);
    lv_obj_set_align(ui_hour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_hour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_hour, 9, 93);
    lv_img_set_zoom(ui_hour, 230);

    ui_dots_group = lv_obj_create(ui_watch_analog);
    lv_obj_set_width(ui_dots_group, 20);
    lv_obj_set_height(ui_dots_group, 50);
    lv_obj_set_x(ui_dots_group, -10);
    lv_obj_set_y(ui_dots_group, 0);
    lv_obj_set_align(ui_dots_group, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_dots_group, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_dots_group, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dots_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dots_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dots_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_dots_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_dots_group, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot16 = lv_obj_create(ui_dots_group);
    lv_obj_set_width(ui_dot16, 10);
    lv_obj_set_height(ui_dot16, 10);
    lv_obj_set_align(ui_dot16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot16, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dot17 = lv_obj_create(ui_dots_group);
    lv_obj_set_width(ui_dot17, 6);
    lv_obj_set_height(ui_dot17, 6);
    lv_obj_set_align(ui_dot17, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dot17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dot17, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dot17, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dot17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_clock_group, ui_event_clock_group, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dot17, ui_event_dot17, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_watch_analog, ui_event_watch_analog, LV_EVENT_ALL, NULL);

}
