// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

//#include "lvgl/lvgl.h"                (Taken out to be more specific for this particular project)
#include <lvgl.h>
#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
void sec_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void left_Animation(lv_obj_t * TargetObject, int delay);
void right_Animation(lv_obj_t * TargetObject, int delay);
void opa_on_Animation(lv_obj_t * TargetObject, int delay);
void dots_Animation(lv_obj_t * TargetObject, int delay);
void top_Animation(lv_obj_t * TargetObject, int delay);
void cloud_Animation(lv_obj_t * TargetObject, int delay);
void blood2_Animation(lv_obj_t * TargetObject, int delay);
void blood1_Animation(lv_obj_t * TargetObject, int delay);
void heart_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_watch_analog
void ui_watch_analog_screen_init(void);
void ui_event_watch_analog(lv_event_t * e);
extern lv_obj_t * ui_watch_analog;
extern lv_obj_t * ui_bg_2;
extern lv_obj_t * ui_battery_group1;
void ui_event_clock_group(lv_event_t * e);
extern lv_obj_t * ui_clock_group;
extern lv_obj_t * ui_sec;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_dots_group;
extern lv_obj_t * ui_dot16;
void ui_event_dot17(lv_event_t * e);
extern lv_obj_t * ui_dot17;
// SCREEN: ui_camera
void ui_camera_screen_init(void);
void ui_event_camera(lv_event_t * e);
extern lv_obj_t * ui_camera;
void ui_event_bg_3(lv_event_t * e);
extern lv_obj_t * ui_bg_3;
extern lv_obj_t * ui_avatar_label;
extern lv_obj_t * ui_dot1;
void ui_event_dot2(lv_event_t * e);
extern lv_obj_t * ui_dot2;
void ui_event____initial_actions0(lv_event_t * e);
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_bg1_png);    // assets/bg1.png
LV_IMG_DECLARE(ui_img_flash_png);    // assets/flash.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets/clockwise_sec.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets/clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets/clockwise_hour.png
LV_IMG_DECLARE(ui_img_bg3_png);    // assets/bg3.png
LV_IMG_DECLARE(ui_img_bg2_png);    // assets/bg2.png
LV_IMG_DECLARE(ui_img_btn_bg_1_png);    // assets/btn_bg_1.png
LV_IMG_DECLARE(ui_img_btn_bg_2_png);    // assets/btn_bg_2.png
LV_IMG_DECLARE(ui_img_btn_bg_3_png);    // assets/btn_bg_3.png
LV_IMG_DECLARE(ui_img_call1_png);    // assets/call1.png
LV_IMG_DECLARE(ui_img_call2_png);    // assets/call2.png
LV_IMG_DECLARE(ui_img_heart2_png);    // assets/heart2.png
LV_IMG_DECLARE(ui_img_s1_png);    // assets/s1.png
LV_IMG_DECLARE(ui_img_s2_png);    // assets/s2.png
LV_IMG_DECLARE(ui_img_s3_png);    // assets/s3.png
LV_IMG_DECLARE(ui_img_s4_png);    // assets/s4.png
LV_IMG_DECLARE(ui_img_s5_png);    // assets/s5.png
LV_IMG_DECLARE(ui_img_s6_png);    // assets/s6.png
LV_IMG_DECLARE(ui_img_s7_png);    // assets/s7.png
LV_IMG_DECLARE(ui_img_s8_png);    // assets/s8.png
LV_IMG_DECLARE(ui_img_s9_png);    // assets/s9.png
LV_IMG_DECLARE(ui_img_wave1_png);    // assets/wave1.png
LV_IMG_DECLARE(ui_img_wave2_png);    // assets/wave2.png

LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
